### PR TITLE
[hansen_singleton] Replace pandas-datareader with direct FRED / Fama-French downloads

### LINKED ISSUE #924: pandas 3.0 (anaconda 2026.06) breaks hansen_singleton lectures via pandas-datareader
## Summary

A full forced execution of every lecture under **anaconda 2026.06** (which upgrades pandas **2.3.3 → 3.0.3**, proposed in #923) fails on `hansen_singleton_1982` and `hansen_singleton_1983`. Both break at **import** of `pandas_datareader`, which is incompatible with pandas 3.0. These lectures execute cleanly on `main` (pandas 2.3.3), so this is a genuine regression introduced by the anaconda 2026.06 upgrade. **Blocks #923.**

## Why normal CI did not catch it

The project builds with `execute_notebooks: "cache"` and PR CI restores the build cache from `main`. jupyter-cache keys on notebook *code*, not on the environment, so a dependency-only PR like #923 reuses cached outputs and never re-executes the notebooks under the new stack — the `preview` check only proves the conda environment *solves*. This failure was found by temporarily forcing a full re-execution under 2026.06 (run [27897336159](https://github.com/QuantEcon/lecture-python.myst/actions/runs/27897336159)).

## Error

```
File .../site-packages/pandas_datareader/data.py:273
--> 273 @deprecate_kwarg("access_key", "api_key")
    274 def DataReader(
TypeError: deprecate_kwarg() missing 1 required positional argument: 'new_arg_name'
```

## Cause

`pandas_datareader` is installed at runtime via `!pip install pandas-datareader` (currently 0.10.0 — last released 2021, effectively unmaintained). It relies on the private pandas API `pandas.util._decorators.deprecate_kwarg`, whose signature changed in pandas 3.0, so the decorator at `pandas_datareader/data.py:273` raises immediately on import. There is no pandas-3.0-compatible `pandas-datareader` release to pin to.

## Affected code

| File | Lines | Code |
|---|---|---|
| `lectures/hansen_singleton_1982.md` | 59, 70, 1037, 1053 | `!pip install pandas-datareader` → `from pandas_datareader import data as web` → `web.DataReader(...)` (FRED + Fama-French) |
| `lectures/hansen_singleton_1983.md` | 83, 1476, 1491 | same pattern |

## Suggested fix

Drop `pandas_datareader` and fetch the series directly:

- **FRED** — `pandas.read_csv` from the FRED CSV download endpoint, or the `fredapi` package.
- **Fama-French** — download the zip from Ken French's data library and parse it.

After migrating, re-run a full forced execution under anaconda 2026.06 to confirm.

## Verification

- **Fails** under anaconda 2026.06 (pandas 3.0.3): run [27897336159](https://github.com/QuantEcon/lecture-python.myst/actions/runs/27897336159) (forced full execution).
- **Passes** under anaconda 2025.12 (pandas 2.3.3) on `main`: the weekly `cache.yml` full build does not fail on these two lectures.

## Also observed — pre-existing, NOT caused by #923 (track separately)

`ar1_bayes` and `ar1_turningpts` also fail in the forced run, but for an unrelated reason: `az.plot_trace(trace, figsize=(17,6))` is rejected by the rewritten arviz plotting backend (`ValueError: Keyword arguments ['figsize'] have been passed as **kwargs but have no active aesthetic mapped to them`). They pull an unpinned arviz via `!pip install arviz pymc` and have been failing on `main`'s weekly cache build for 5+ weeks, independent of the pandas upgrade.

### PR DESCRIPTION
**Pull request by mmcky**
Closes #924.

> **Stacked on #926 — merge that first.** This PR reads a vendored data snapshot that #926 adds to `main`. Until #926 lands, this PR's CI will fail (the `…/main/…` data URL 404s); it goes green once #926 is merged.

## Problem

`hansen_singleton_1982` and `hansen_singleton_1983` fail to execute under anaconda 2026.06 / pandas 3.0 (surfaced by the forced full execution in #923). Both `!pip install pandas-datareader` and import it, but `pandas-datareader` 0.10.0 (unmaintained since 2021) relies on the private pandas API `pandas.util._decorators.deprecate_kwarg`, whose signature changed in pandas 3.0, so it dies at import:

```
TypeError: deprecate_kwarg() missing 1 required positional argument: 'new_arg_name'
```

## Approach

Following discussion, instead of fetching from the data providers at build time, the data is **vendored**:

- **#926** adds `_static/lecture_specific/hansen_singleton_198{2,3}/` — a `make_data.py` maintenance script (builds the dataset from FRED + Ken French), the frozen `*_data.csv` snapshot, and a `README.md`.
- **This PR** removes the `pandas-datareader` dependency (and the inline fetch helpers) and collapses each lecture's hidden data cell to a single `pd.read_csv(<raw GitHub URL>)` of that snapshot, selecting the columns it needs.

This matches the existing vendored-data convention used by `mle`, `ols`, and `pandas_panel`, keeps the build reproducible, and removes the live-fetch fragility (the flaky-network class that also bit `ols`).

## Verification

| Check | Result |
|---|---|
| `make_data.py` output vs old `pandas-datareader` path (pandas 2.3.3) | byte-identical FRED + Fama-French data |
| Lectures' code cells reading the vendored CSV, `FutureWarning`/`DeprecationWarning` → error | run clean (pandas-3.0 safe) |
| Resulting frames | 239 rows (1959-02 → 1978-12), expected columns, moments unchanged |

Net effect on the lectures: **−236 / +34** lines — the data machinery moves out to the maintenance scripts.

## Note

The two `ar1_*` lectures that also fail under a forced run are a separate, pre-existing arviz issue, out of scope here.

### CODE REVIEW

**Comment by mmcky** [comment]
Updated to the vendored-data pattern discussed: the data + maintenance script + README now live in #926, and this PR just reads the snapshot from GitHub. **Merge #926 first**; this PR's CI will be red until then (the `/main/` data URL 404s until #926 lands), after which I'll re-trigger and confirm green.

File: lectures/hansen_singleton_1982.md [hunk 1]
```diff
@@ -1000,80 +985,30 @@ Because the Ken French return is not identical to the original CRSP NYSE value-w
...
-    ]
-    return out[required_cols].copy()
+    The data are a vendored snapshot built by the maintenance script at
+    ``_static/lecture_specific/hansen_singleton_1982/make_data.py``, which
+    constructs them from FRED and the Ken French data library.
+    """
+    frame = pd.read_csv(DATA_URL, index_col=0, parse_dates=True)
+    start = pd.Timestamp(start).to_period("M").to_timestamp("M")
+    end = pd.Timestamp(end).to_period("M").to_timestamp("M")
+    return frame.loc[start:end]
```
[the remark this answers is not in the document]
Comment (mmcky) [reply lectures/hansen_singleton_1982.md]: Fixed in 135e0ddb5 — the vendored CSV is now read once into a cell-scope `_data` and `load_hs_monthly_data` returns a sliced `.copy()`, so repeated calls don't re-fetch or re-parse.

File: lectures/hansen_singleton_1983.md [hunk 2]
```diff
@@ -1439,85 +1425,32 @@ While Hansen-Singleton use CRSP value-weighted NYSE returns, we use the Ken Fren
...
-    ]
-    return out[required_cols].copy()
+    The data are a vendored snapshot built by the maintenance script at
+    ``_static/lecture_specific/hansen_singleton_1983/make_data.py``, which
+    constructs them from FRED and the Ken French data library.
+    """
+    frame = pd.read_csv(DATA_URL, index_col=0, parse_dates=True)
+    start = pd.Timestamp(start).to_period("M").to_timestamp("M")
+    end = pd.Timestamp(end).to_period("M").to_timestamp("M")
+    return frame.loc[start:end]
```
[the remark this answers is not in the document]
Comment (mmcky) [reply lectures/hansen_singleton_1983.md]: Fixed in 135e0ddb5 — `_data = pd.read_csv(DATA_URL, ...)` is read once at cell scope and `load_hs_monthly_data` slices a copy of it. Verified the CSV is now fetched only once even though both `get_estimation_data` and `get_tbill_estimation_data` call it.

File: lectures/hansen_singleton_1982.md [hunk 3]
```diff
@@ -1018,6 +1007,55 @@ def to_month_end(index):
...
+    """
+    Download the monthly Fama-French research factors directly from the Ken
+    French data library (replaces pandas-datareader's "famafrench" reader).
+    Returns a month-``Period``-indexed DataFrame with values in percent.
+    """
+    url = ("https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/"
+           "F-F_Research_Data_Factors_CSV.zip")
+    with urllib.request.urlopen(url) as response:
+        archive = zipfile.ZipFile(io.BytesIO(response.read()))
+    text = archive.read(archive.namelist()[0]).decode("utf-8")
```
[the remark this answers is not in the document]
Comment (mmcky) [reply lectures/hansen_singleton_1982.md]: This inline fetch code was removed from this PR when the lectures switched to reading a vendored CSV snapshot, so it no longer exists here. The FRED/Fama-French download now lives in PR #926's `make_data.py`, where the `zipfile.ZipFile(...)` is wrapped in a `with` block in d834b09f5.

File: lectures/hansen_singleton_1983.md [hunk 4]
```diff
@@ -1457,6 +1446,55 @@ def to_month_end(index):
...
+    """
+    Download the monthly Fama-French research factors directly from the Ken
+    French data library (replaces pandas-datareader's "famafrench" reader).
+    Returns a month-``Period``-indexed DataFrame with values in percent.
+    """
+    url = ("https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/"
+           "F-F_Research_Data_Factors_CSV.zip")
+    with urllib.request.urlopen(url) as response:
+        archive = zipfile.ZipFile(io.BytesIO(response.read()))
+    text = archive.read(archive.namelist()[0]).decode("utf-8")
```
[the remark this answers is not in the document]
Comment (mmcky) [reply lectures/hansen_singleton_1983.md]: Same as the 1982 case: the inline download was removed from this PR (the lectures now read a vendored CSV). The code moved to PR #926's `make_data.py`, where the `ZipFile` is now opened with a context manager in d834b09f5.

**Comment by mmcky** [comment]
Heads-up from the data validation on #926 (full details there): the vendored series are identical to the live-fetch series to 2.2e-16, and the `hansen_singleton_1982` figures render pixel-identical. One cosmetic effect to expect — when this PR re-executes `hansen_singleton_1983` on the vendored CSV, its residual-diagnostic figure will shift slightly. That is the non-convex MLE multi-start landing on a marginally better optimum under the last-bit data round-trip (log-likelihood 1209.33 → 1209.43; same lags rejected / not rejected). Flagging so the figure diff on re-execution isn't a surprise; it is not a regression.
